[package]
name = "git-repo-lang-trend-rs"
version = "0.1.0"
authors = ["Martin Nordholts <enselic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
