name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: ubuntu-22.04 }
          - { name: macos-15 }
    runs-on: ${{ matrix.os.name }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install
        run: |
          pip install .
      - name: Install dev dependencies
        run: |
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          pytest -vv
      - name: Test with shallow clone
        run: |
          tag=v0.0.3-pip
          tmpdir=/tmp/shallow
          git clone --branch ${tag} --depth 2 https://github.com/Enselic/git-repo-language-trends.git ${tmpdir}
          GIT_DIR=${tmpdir} git-repo-language-trends --first-commit=${tag} -o=shallow.csv
          cat shallow.csv
          cmp shallow.csv tests/data/expected-shallow.csv
      - name: Generate default plots for manual visual regression testing
        run: |
          export OUTDIR=grlt-samples
          ./scripts/generate-png-and-svg-samples.sh
