name: CI/CD

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  cicd:
    name: CI/CD
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: ubuntu-18.04 }
          - { name: macos-10.15 }
          - { name: windows-2019 }
    runs-on: ${{ matrix.os.name }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7 # for test, 3.6 for app, TODO: Solve this better
      - name: Install dependencies
        run: |
          python3 -m pip install pygit2 matplotlib
      - name: Install dev dependencies
        run: |
          python3 -m pip install flake8 pytest
      - name: Lint with flake8
        run: |
          flake8 --max-line-length=110
      - name: Test with pytest
        run: |
          pytest -vv
      - name: Build release
        id: release
        run: |
          PROJECT_VERSION=$(git describe --dirty) echo TODO
      - name: Package release build
        id: package
        run: |
          echo TODO
      - name: Upload artifact
        run: |
          echo TODO
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo TODO
