name: CI/CD

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  cicd:
    name: CI/CD
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: ubuntu-18.04 }
          - { name: macos-10.15 }
          - { name: windows-2019 }
    runs-on: ${{ matrix.os.name }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7 # for test, 3.6 for app, TODO: Solve this better
      - name: Install
        run: |
          # "We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default."
          pip install --use-feature=in-tree-build .
      - name: Install dev dependencies
        run: |
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          pytest -vv
      - name: Test with shallow clone
        run: |
          tag=v0.0.3-pip
          tmpdir=/tmp/shallow
          git clone --branch ${tag} --depth 2 https://github.com/Enselic/git-repo-language-trends.git ${tmpdir}
          GIT_DIR=${tmpdir} git-repo-language-trends --first-commit=${tag} -o=shallow.csv
          cat shallow.csv
          cmp shallow.csv tests/data/expected-shallow.csv
      - name: Build release
        id: release
        run: |
          PROJECT_VERSION=$(git describe --dirty) echo TODO
      - name: Package release build
        id: package
        run: |
          echo TODO
      - name: Upload artifact
        run: |
          echo TODO
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo TODO
