name: CI/CD

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cicd:
    name: CI/CD
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: ubuntu-18.04 }
          - { name: macos-10.15 }
          - { name: windows-2019 }
    runs-on: ${{ matrix.os.name }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        run: |
          echo TODO
      - name: Build
        run: |
          echo TODO
      - name: Test
        run: |
          echo TODO
      - name: Build release
        id: release
        run: |
          PROJECT_VERSION=$(git describe --dirty) echo TODO
      - name: Package release build
        id: package
        run: |
          echo TODO
      - name: Upload artifact
        run: |
          echo TODO
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo TODO
