name: CICD

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-test-release-package-upload:
    name: Lint, Build, Test, Build release, Package, Upload
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: ubuntu-18.04 }
          - { name: macos-10.15 }
          - { name: windows-2019, bin-suffix: .exe }
    runs-on: ${{ matrix.os.name }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          cargo clippy --locked -- --deny warnings
      - name: Build
        run: |
          cargo build --locked
      - name: Test
        run: |
          cargo test --locked
      - name: Build release
        id: release
        run: |
          cargo build --release --locked
          echo ::set-output name=BIN_PATH::./target/release/git-repo-language-trends${{ matrix.os.bin-suffix }}
      - name: Strip release build
        run: |
          if command -v strip; then strip ${{ steps.release.outputs.BIN_PATH }}; fi
      - name: Package release build
        id: package
        run: |
          PACKAGE_NAME=git-repo-language-trends_${{ matrix.os.name }}.zip
          echo ::set-output name=PACKAGE_NAME::${PACKAGE_NAME}
          zip $PACKAGE_NAME ${{ steps.release.outputs.BIN_PATH }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.PACKAGE_NAME }}
          path: ${{ steps.package.outputs.PACKAGE_NAME }}
