name: PyPI upload

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  pypi-upload:
    name: PyPI upload
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install build twine
      - name: Build
        run: |
          python3 -m build
      - name: PyPI upload
        run: |
          export TWINE_USERNAME=__token__
          export TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}
          python3 -m twine upload dist/*
          unset TWINE_PASSWORD
          unset TWINE_USERNAME
